apiVersion: apps/v1
kind: Deployment
metadata:
  name: leena-deployment
  labels:
    app: leenaapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leenaapp
  template:
    metadata:
      labels:
        app: leenaapp
    spec:
      containers:
      - name: leena-container
        image: leenahub/intel-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: leenaapp
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: leenaapp 
